name: Update Metal Prices

on:
  workflow_dispatch:

  schedule:
    - cron: '*/15 * * * *'

permissions:
  contents: write

jobs:
  update:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install packages
        run: npm install

      - name: Run updater
        env:
          GOLD_API_KEY: ${{ secrets.GOLD_API_KEY }}
        run: node scripts/update.js

      - name: Commit updated JSON

        run: |

          git config --global user.name "GitHub Actions"

          git config --global user.email "github-actions@github.com"

          git add data/metals.json

          git diff --staged --quiet || git commit -m "Update metal prices"

          git push
